spring.application.name=Modern Coding
server.address=127.0.0.1
server.port=8085
spring.datasource.url=jdbc:h2:mem:moderncoding;MODE=PostgreSQL;NON_KEYWORDS=KEY;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.flyway.enabled=true
spring.h2.console.enabled=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false
server.error.include-message=never
server.error.include-stacktrace=never
